# docker-compose.yml
version: '3.9'

services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      TZ: Asia/Bangkok
      POSTGRES_DB: gymtrack_db
      POSTGRES_USER: gymtrack_user
      POSTGRES_PASSWORD: securepassword
    ports: [5432:5432]
    volumes: [postgres-data:/var/lib/postgresql/data]
  redis:
    image: redis:7-alpine
    restart: on-failure
    environment:
      TZ: Asia/Bangkok
    volumes: [redis-data:/data]
    ports: [6379:6379]
    command: --appendonly yes --requirepass --timeout 0
volumes:
  postgres-data:
  redis-data:
