// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/gofiber/fiber/v2"
	"github.com/treewalkr/gymtrack/internal/application"
	"github.com/treewalkr/gymtrack/internal/infrastructure/persistence"
	"github.com/treewalkr/gymtrack/internal/infrastructure/server"
	"github.com/treewalkr/gymtrack/internal/interfaces/handlers"
)

// Injectors from wire.go:

func InitializeServer(dsn string) (*fiber.App, error) {
	userRepository, err := persistence.NewUserRepository(dsn)
	if err != nil {
		return nil, err
	}
	userService := application.NewUserService(userRepository)
	userHandler := handlers.NewUserHandler(userService)
	app := server.SetupRouter(userHandler)
	return app, nil
}
